# Generated by Django 4.1.6 on 2023-02-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAIN_LINKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TOP_BAR_LINKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_bar_name', models.CharField(max_length=200)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.main_links')),
            ],
        ),
    ]
