# Generated by Django 4.1.6 on 2023-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='storage',
            name='longname',
            field=models.CharField(db_column='longname', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='responsible_person',
            field=models.CharField(db_column='responsible_person', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='room',
            field=models.CharField(db_column='room', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='shortname',
            field=models.CharField(db_column='shortname', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='title_de',
            field=models.CharField(db_column='title_de', max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='title_en',
            field=models.CharField(db_column='title_en', max_length=200),
        ),
        migrations.AlterModelTable(
            name='storage',
            table='storage',
        ),
    ]
