# Generated by Django 4.1.6 on 2023-02-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_storage_options_alter_storage_longname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'managed': False},
        ),
    ]
