# Generated by Django 4.1.6 on 2023-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_delete_electronicparts_delete_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronicparts',
            fields=[
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('part', models.CharField(db_collation='utf8mb3_general_ci', max_length=256)),
                ('datasheet', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=32, null=True)),
                ('box_num', models.IntegerField(blank=True, null=True)),
                ('reichelt_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=32, null=True)),
                ('reichelt_num', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=32, null=True)),
                ('link_reichelt', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_conrad', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_voelkner', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_farnell', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_rs', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_mouser', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_digikey', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('link_other', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('remainder', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compartment', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=32, null=True)),
            ],
            options={
                'db_table': 'electronicparts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('room', models.CharField(db_collation='utf8mb3_general_ci', max_length=32, primary_key=True, serialize=False)),
                ('longname', models.CharField(db_collation='utf8mb3_general_ci', max_length=32)),
                ('shortname', models.CharField(db_collation='utf8mb3_general_ci', max_length=32)),
                ('responsible_person', models.CharField(max_length=32)),
                ('title_en', models.CharField(db_collation='utf8mb3_general_ci', max_length=32)),
                ('title_de', models.CharField(db_collation='utf8mb3_general_ci', max_length=32)),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
    ]
