# Generated by Django 4.1.6 on 2023-02-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_electronicparts_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datasheet',
        ),
    ]
