# Generated by Django 4.1.7 on 2023-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_datasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('send_to_this', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='datasheet',
            field=models.FileField(upload_to=''),
        ),
    ]
